package com.infy.customerRewards.entity;

import java.util.List;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Entity class representing a customer in the rewards system.
 * Stores customer information and maintains a one-to-many relationship with transactions.
 * 
 * @author Infy
 * @version 1.0
 * @since 2024
 */
@Data
@Entity
@Table(name = "customers")
public class Customer {
	
	/**
     * Unique identifier for the customer.
     * Automatically generated by the database using identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Name of the customer.
     * Required field for customer identification.
     */
    private String custName;
    
    /**
     * Phone number of the customer.
     * Used as contact information and potentially for authentication.
     */
    private String phoneNo;
    
    /**
     * List of transactions associated with this customer.
     * Maintains bidirectional relationship with Transaction entity.
     * Cascades all operations and removes orphans automatically.
     */
    @OneToMany(mappedBy = "customer", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Transaction> transactions;
    
    /**
     * Gets the unique identifier of the customer.
     * @return the customer ID
     */
    public Long getId() {
        return id;
    }
    
    /**
     * Sets the unique identifier of the customer.
     * @param id the customer ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }
    
    /**
     * Gets the customer's name.
     * @return the customer name
     */
    public String getCustName() {
        return custName;
    }
    
    /**
     * Sets the customer's name.
     * @param custName the customer name to set
     */
    public void setCustName(String custName) {
        this.custName = custName;
    }
    
    /**
     * Gets the customer's phone number.
     * @return the phone number
     */
    public String getPhoneNo() {
        return phoneNo;
    }
    
    /**
     * Sets the customer's phone number.
     * @param phoneNo the phone number to set
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    
    /**
     * Gets the list of transactions associated with this customer.
     * @return list of customer transactions
     */
    public List<Transaction> getTransactions() {
        return transactions;
    }
    
    /**
     * Sets the list of transactions for this customer.
     * Replaces the current transaction list with the provided list.
     * @param transactions the list of transactions to set
     */
    public void setTransactions(List<Transaction> transactions) {
        this.transactions = transactions;
    }
}
