package com.infy.customerRewards.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.time.LocalDate;

/**
 * Entity class representing a transaction in the rewards system.
 * Stores transaction details and maintains a many-to-one relationship with customers.
 * Each transaction is associated with a customer and used for reward point calculations.
 * @author Infy
 * @version 1.0
 * @since 2024
 */
@Data
@Entity
@Table(name = "transactions")
public class Transaction {
    
    /**
     * Unique identifier for the transaction.
     * Automatically generated by the database using identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    /**
     * Date when the transaction occurred.
     * Used for filtering transactions by time period and monthly reward calculations.
     */
    private LocalDate date;
    
    /**
     * Product or service purchased in this transaction.
     * Describes what was bought in the transaction.
     */
    private String product;
    
    /**
     * Monetary amount of the transaction.
     * Used as the basis for calculating reward points.
     */
    private Double amount;

    /**
     * Customer who made this transaction.
     * Maintains bidirectional relationship with Customer entity.
     * Uses lazy fetching for performance optimization.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    /**
     * Gets the unique identifier of the transaction.
     * @return the transaction ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the transaction.
     * @param id the transaction ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the date when the transaction occurred.
     * @return the transaction date
     */
    public LocalDate getDate() {
        return date;
    }

    /**
     * Sets the date when the transaction occurred.
     * @param date the transaction date to set
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }

    /**
     * Gets the product or service purchased in this transaction.
     * @return the product name
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the product or service purchased in this transaction.
     * @param product the product name to set
     */
    public void setProduct(String product) {
        this.product = product;
    }

    /**
     * Gets the monetary amount of the transaction. 
     * @return the transaction amount
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * Sets the monetary amount of the transaction.
     * @param amount the transaction amount to set
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * Gets the customer who made this transaction.
     * @return the associated customer entity
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the customer who made this transaction.
     * Establishes the relationship between transaction and customer.
     * @param customer the customer to associate with this transaction
     */
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
}
